### PR TITLE
Update to Julia 1.6 release

### PR DESCRIPTION
**Pull request by bkamins**
I will try to check if any other files require updating

### CODE REVIEW

**Comment by bkamins** [comment]
@jangorecki are the changes OK?

**Comment by bkamins** [comment]
I have also added an option to launch Julia using multiple threads (soon this will be used by DataFrames.jl).

**Comment by bkamins** [comment]
@jangorecki - could I help somehow to help you with this?

I also have a question. In the PR I have proposed to use all available logical cores on the machine. Do you have the same setting in other frameworks, or limit it to the number of physical cores? (to ensure we compare the same thing on different platforms). Thank you!

**Review by nalimilan — APPROVED** [review]

**Comment by jangorecki** [comment]
I am recently on another project, and currently on vacations. Anyway I will try to push this change sooner as it should be pretty simple. As for the number of cores you have to look scripts for configuration. DT uses all, other tools I don't remember, configuration was contributed by members of those communities or left default/all.

**Comment by bkamins** [comment]
Thank you for the response. Let us use the default then as proposed in this PR.

**Pull request merged**
