### PR TITLE
julia: work around hang when loading CSV

### PR DESCRIPTION
**Pull request by nalimilan**
Only treat columns as categorical when there are 5% unique value, i.e. at least 500 rows per group. This works around a hang when loading the 50GB file due to the slowness of adding and sorting 10M levels.

See https://github.com/h2oai/db-benchmark/pull/51#issuecomment-444407799.

### CODE REVIEW

**Comment by bkamins** [comment]
Yes - this should be good enough. Thanks.

**Comment by jangorecki** [comment]
Thanks for PR.
We recently added 3 other datasets. Actually same dataset but different cardinalities and sortedness. In case of 1e9 rows and K=2 (cardinality) one of the questions result into 431 M groups. Is this PR going to handle that? 5% of 413M will be 20+M. I would prefer to turn off categoricals till it is fixed because hang runs takes "a lot" of time before eventually I decide to kill them.
Timings of those others datasets are presented in a table below the main plots.

**Comment by nalimilan** [comment]
What's the number of rows per group in that scenario? IIUC there are 2 rows per group and 1e9 rows, so that would mean the column wouldn't be parsed as categorical with this PR. That would only happen if there are less than 20M groups (which would still hand when loading the data, but is this scenario tested?).

**Comment by jangorecki** [comment]
In above case it would be around 2.3 rows per group. The sixth question that is coming is likely to return 1 row per group. For now will run using safer option `categoricals=false`, and when machine will be idle I will try your PR.

**Comment by nalimilan** [comment]
OK, thanks. With 2.3 rows or 1 row per group, there should be no problem with this PR.

**Comment by jangorecki** [comment]
Benchmark report has been refreshed, currently presented timings for DataFrames.jl are based on strings, not categoricals. Will try to run `categoricals=0.05` soon.

**Comment by bkamins** [comment]
Thanks

**Comment by nalimilan** [comment]
BTW, have you considered adding benchmarks for custom functions which cannot be special-cased like `sum` and `mean`? That's an area where Julia may have an advantage compared with implementations which are based on C under the hood and which can only be fast for standard operations. (That said, we really need to add optimized methods for `sum`, which is taking most of the time on these benchmarks.)

**Comment by jangorecki** [comment]
@nalimilan agree, added #57

**Pull request merged**
