### PR TITLE
Update Julia benchmarks

### PR DESCRIPTION
**Pull request by bkamins**
@jangorecki this PR updates the Julia `by` benchmarks to the DataFrames.jl package v0.15.0 syntax.

@nalimilan - can you please double check if I have updated everything correctly?

### CODE REVIEW

**Comment by bkamins** [comment]
Actually each benchmark is run twice.
@jangorecki: which timing do you take for comparisons?

**Comment by bkamins** [comment]
Thank you - now I see it 😄.

As for data loading I understand that only 50GB case fails (for 0.5 and 5GB I can see the results) - right?

Also can you please let us know when you plan to re-run the benchmarks so that we can see if the CSV.jl still fails?

Finally, if it still fails, could you please report an issue on https://github.com/JuliaData/CSV.jl indicating which file failed to load. I am sure that @quinnj will be willing to fix it.

**Comment by nalimilan** [comment]
Thanks. It's good to show both the first and second run indeed.

BTW, could you call this "DataFrames.jl" instead of "juliadf"? We don't use the latter name anywhere.

**Comment by jangorecki** [comment]
@bkamins it was not failing but hanging, first script was processed fine but then the next one, after closing julia process, resetting env var to point to another dataset, and starting same julia script again was hanging on loading csv. Even when size was the same. Need to investigate this. AFAIR it started to happens when I switched to `categorical=true`, but not sure if it is actually related as the first script was finishing successfully, all next ones were hanging.
@nalimilan done in 7e43d0e1c0a3f745394be60bb0182c6518fb47c2

**Comment by nalimilan** [comment]
Thanks.

The hang is a known problem with `categorical=true`, we resort the levels for each new level, which it terrible when there are 10M levels. I'd recommend using `categorical=false` for that case, categorical arrays are not designed to be more efficient with that many levels anyway. (But I'll fix that, it's easy.)

**Comment by bkamins** [comment]
@nalimilan: so can you add a PR to https://github.com/h2oai/db-benchmark and set `categorical` to `true` or `false` as appropriate or we leave it as is here and fix categorical with many levels?

**Comment by jangorecki** [comment]
@nalimilan please fix, because of that issue julia is at the moment disabled from runs.

Is it possible to use development versions of julia packages easily? I now run [`using Pkg; Pkg.update();`](https://github.com/h2oai/db-benchmark/blob/master/juliadf/init-juliadf.sh) so it updates to stable released version. Our preferred way is to run benchmark on development versions, so users and devs can see progress when pushing some improvements. It will be even more valuable when #46 resolved. We currently do it for data.table, dplyr and (py)datatable. If there is no easy way for this I will proceed with `categorical=false` for now.

**Comment by bkamins** [comment]
> Is it possible to use development versions of julia packages easily?

Yes. You can make Julia track master branch of some package by writing:
```
using Pkg
Pkg.add(PackageSpec(name="PackageName", rev="master"))
```
However, I would say that this is not needed, as all the packages are under a fast release cycle as they all are in development phase still.

Also in our case e.g. categorical type is defined in the CategoricalArrays.jl package and probably the fix we discuss will be made there by @nalimilan, but normally you do not install this package directly and checking out master of CSV.jl or DataFrames.jl would not fix it anyway.

**Comment by nalimilan** [comment]
I've filed https://github.com/h2oai/db-benchmark/pull/53, since the fix might take a bit to prepare, merge and release. Anyway using categorical columns doesn't really change performance currently when there are only 100 rows per group. When we're able to deal better with this I'll make another PR.

**Pull request merged**
