### PR TITLE
up Julia to 1.5.0 release

### PR DESCRIPTION
**Pull request by bkamins**
Hopefully all will go cleanly.

### CODE REVIEW

**Comment by jangorecki** [comment]
Report updated.

**Comment by bkamins** [comment]
Thank you!

Can you please remind me when I can check history?

**Comment by bkamins** [comment]
Also "Environment configuration" description shows "Julia 1.4.1", but I guess it is just something I have missed to update when making the PR bumping the Julia version.

**Comment by jangorecki** [comment]
I just pushed a commit to update version number on report, so after next run it should show 1.5.0 there already.

https://h2oai.github.io/db-benchmark/history.html

**Pull request merged**
