### PR TITLE
Add helper class BenchmarkTask to simplify python benchmarking code

### PR DESCRIPTION
**Pull request by st-pasha**
* Reduce code repetition in `groupby-pydatatable.py`;
* Enable multi-column group-by's (Question 2);
* Created class `BenchmarkTask` in "helpers.py" to make writing benchmarks easier for all python solutions (however this class currently used in "groupby-pydatatable.py" only: we could use it more widely once it is verified that it works correctly).

### CODE REVIEW

**Comment by jangorecki** [comment]
I understand `**` is very fast but 17% speed up is quote significant, probably not noticeable in our `groupby` questions but for others tasks might make difference. In such a case we would then need to investigate what is the overhead/underhead in other technologies we are using, and use faster way, to be fair. Benefits you listed are quite correct and useful, but would need to be done for every language we use, and examined for performance impact. Keeping code sequential, including repetition, makes it easier to be fair in comparison.

**Comment by st-pasha** [comment]
The difference here is not 17%, the difference is ~1 microsecond. A function call adds a more-or-less constant overhead, but otherwise does not affect timing.
Here's an example with sorting 1,000,000 numbers:
```
>>> import time, random
>>> def foo(src):
...   return sorted(src)
... 
>>> src1 = [random.randint(1, 10000) for _ in range(1000000)]
>>> t0 = time.time(); y = foo(src1); print(time.time() - t0)
0.4126260280609131
>>> t0 = time.time(); y = foo(src1); print(time.time() - t0)
0.42340517044067383
>>> t0 = time.time(); y = foo(src1); print(time.time() - t0)
0.42221689224243164
>>> t0 = time.time(); y = foo(src1); print(time.time() - t0)
0.4222731590270996
>>> t0 = time.time(); y = sorted(src1); print(time.time() - t0)
0.42013001441955566
>>> t0 = time.time(); y = sorted(src1); print(time.time() - t0)
0.4268798828125
>>> t0 = time.time(); y = sorted(src1); print(time.time() - t0)
0.4236748218536377
>>> t0 = time.time(); y = sorted(src1); print(time.time() - t0)
0.4182240962982178
```
As you can see, the difference between 2 use cases is lost in the statistical noise when the run time of the task is on the order of magnitude of a second.
And these are the only kinds of tasks that we consider anyways.

**Comment by jangorecki** [comment]
Numbers you provided are ~17% diff. I know speed diff won't be noticeable, but we need to be fair and investigate other solutions for such wrappers. Keeping code simple and avoiding such wrappers scales readability better for new solutions and eventually languages we will need to use. For people who don't know julia or any other language it is generally easier to follow code having less wrappers, do they don't have to lookup pieces. It is actually valid even for me looking at your PR, I can understand it but it is easier to follow script as is now.

**Comment by st-pasha** [comment]
Ok, I kinda see your point, but then I'm not sure I agree.

We're comparing 2 generic styles of writing the code. Style 1:
```
benchmark(
  line-of-code
)
```
and Style 2: 
```
....
.... lots of preparatory code
....
line-of-code
....
.... lots of epilogue code
....
```

It appears to me that, purely from readability standpoint, Style 1 is better at answering the question "what is being measured?", regardless of the proficiency of the reader. Certain degree of trust, however, is required to accept that the `benchmark()` function does what it's supposed to do. Style 2 might be preferrable to answer the question "how it is being measured?", but only for a person not proficient with the language (nothing derogatory, we are all not profficient in most of the languages).
If the question is "is it measured fairly and equally?", then Style 1 wins again.

In terms of maintenance, I believe Style 1 again makes it easier to update questions / add new questions / modify the general benchmarking procedure; except maybe with respect to modifying the connecting code, but that rarely needs to be updated. Finally, the benchmarking code will become more complex over time, only Style 1 ensures that this complexity will not explode exponentially. 

I maybe missing something, but given the reasons above, it appears to me that the advantages of Style 1 considerably outweigh those of Style 2. 

Finally, I'm not claiming that this PR actually achieves a stylistic perfection, but it is definitely closer. Also, the ideal style doesn't have to be attained in all languages at once. It may not even be possible in some languages (say, SQL).

**Comment by jangorecki** [comment]
You nailed it well

>  Certain degree of trust, however, is required to accept that the `benchmark()` function does what it's supposed to do.

And this is exactly the place where I am confident to use `system.time` which is included in base R. But not to develop `system.time` functions in python or julia. In the first case people have to trust R. In the latter then need to trust us. For me it means that they have to go and read our wrapper. And also because of that I am not wrapping R calls into more generic executions like `for (run in 1:2)`.
```
benchmark(
  line-of-code
)
```
is very nice way, but would require to maintain wrappers in every language. AFAIR it is not possible in python because `line-of-code` will get evaluated before `benchmark` function starts. `Question1(x, filename).run()` is pretty far from that.
Having highly parametrized script in one solution but not others will make it much more difficult to compare and map processes between languages, which I see as big advantages. Not only for readability but also for educational purpose to see how it can be done in another language.

Yesterday I spotted a benchmark in which, precisely because of parametrizing code so it can be called in a more generic way, the sub-optimal processes were benchmarked, see https://github.com/STATWORX/blog/issues/2

**Comment by st-pasha** [comment]
> And this is exactly the place where I am confident to use system.time which is included in base R. But not to develop system.time functions in python or julia.

Of course. But my PR does not reinvent the timer: there is standard library `time.time()` for that. What it does is it collects common functionality in a reusable function. Note that the previous code also did that, only to a lesser degree: `write_log`, `memory_usage`, `make_chk`, `flatten` all implement custom common functionality. My PR merely makes the next logical step.

>  Question1(x, filename).run() is pretty far from that.
I could convert this to `Question1(x, filename).benchmark()`, or `benchmark(Question1, x, filename)`. The `filename` is only needed there for logging purposes. So if the logger itself would remember the filename, we won't need to pass it.

> AFAIR it is not possible in python because line-of-code will get evaluated before benchmark function starts.

This is precisely why we encapsulate each question in a class: then code evaluation can be done at the appropriate time.

> Having highly parametrized script in one solution but not others will make it much more difficult to compare and map processes between languages.

A change has to start somewhere. I'm not a big fan (anymore) of grandiose changes across the entire code base. If this approach proves to be useful, we can extend it to other questions, and other solutions in due time.

> Yesterday I spotted a benchmark in which, precisely because of parametrizing code so it can be called in a more generic way, the sub-optimal processes were benchmarked, see STATWORX/blog#2

This is where I totally agree with you. The function they were benchmarking was not pure, using some global `filter` variable (which confusingly seem to refer both to a column name, and to a value being compared to). And it seems their fix even made it worse (at least from readability standpoint): now the code that is benchmarked is parsed/eval'd on the spot, and it's even harder to figure out what it does, and whether it's correct.

**Comment by jangorecki** [comment]
closing as we want to avoid custom wrappers in benchmark scripts

**Pull request closed without merging**
