### PR TITLE
Fix Julia setup

### PR DESCRIPTION
**Pull request by bkamins**

### CODE REVIEW

**Comment by bkamins** [comment]
What I change here:
* up Julia to 1.6.1
* remove `-S` shebang, instead use `export JULIA_NUM_THREADS=20`

@jangorecki The only thing I was not sure was how you wanted to handle the `Threads.nthreads()` reporting form the groupby-juliadf.jl and join-juliadf.jl, so I have not added it?

**Comment by bkamins** [comment]
also there was a typo in CSV reader kwarg name which I fixed.

**Comment by bkamins** [comment]
I had also to fix the `big` name, as it clashes with the standard function in Julia:
```
  big(x)

  Convert a number to a maximum precision representation (typically BigInt or BigFloat). See BigFloat for information about some pitfalls with
  floating-point numbers.
```
(the issue is exposed when enabling multi-threading)

For consistency I have added `_df` suffix to all `DataFrame` names in the join benchmarks.

**Review by nalimilan — APPROVED** [review]

**Comment by bkamins** [comment]
@jangorecki - is all I propose clear and acceptable? Thank you!

**Review by jangorecki — APPROVED** [review]
Yes, all is clear. Benchmark machine is already running another project benchmark which takes one week so we have to wait few more days before bringing back db-benchmark there.

`Threads.nthreads()` I will use only once to ensure that 20 threads are being used.

As for environment variable I will move it somewhere else because run.conf should not have per solution configurations. In R we use .Renviron file. Is there anything similar in julia?

**Comment by bkamins** [comment]
>  Is there anything similar in julia?

Normally you pass `-t 20` argument, but in your OS configuration it does not work unfortunately because the `-S` is not supported.

Alternatively, as discussed earlier, you can create intermediate .sh files containing respectively:
* groupby-juliadf.sh
```
#!/bin/bash
julia -t 20 groupby-juliadf.jl
```
* join-juliadf.sh
```
#!/bin/bash
julia -t 20 join-juliadf.jl
```
(and then the shebang line can be removed from the .jl files)
and call these .sh files from the launcher.

Would this approach work for you?

**Comment by jangorecki** [comment]
Env var looks to be more simple.

**Comment by bkamins** [comment]
OK - so I understand it can be left as is now?

**Comment by jangorecki** [comment]
as is now is good

**Comment by jangorecki** [comment]
It is a pity that it is not possible to change number of threads after julia is already started. I will have to use extra shell script as you suggested. Setting env var is more neat but will not work when running single script with `_launcher/solution.R` script.

**Comment by bkamins** [comment]
Indeed it is a pity. I really wish it was possible to change number of threads that Julia process uses (and AFAICT it might be possible in the future, but not currently). Thank you for working on it.

**Comment by bkamins** [comment]
@jangorecki - I understand that the current timings shown on the page (that are dated for May 7, 2021 are still old for DataFrames.jl - right? Does the date next to the package version show when the test was run?)

**Comment by jangorecki** [comment]
On the top of benchplot there are versions and dates. Julia is already running now so till tomorrow should be on the report.

**Pull request merged**
